import Head from 'next/head';
import TitleHero from '@heros/TitleHero';
import AboutMe from '@modules/AboutMe';
import Footer from '@elements/Footer';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TitleHero />
        <AboutMe />
        <Footer />
      </main>

    </div>
  )
}

