import Head from 'next/head';
import Hero from '@modules/Hero/Hero';
import AboutMe from '@modules/AboutMe';
import Footer from '@elements/Footer';
import MyProjects from '@modules/MyProjects';
import projectCardData from '@mocks/data/projectCardData';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero /> 
        <AboutMe />
        <MyProjects projects={projectCardData}/>
      </main>
      <Footer />
    </div>
  )
}

